# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc 'Build the Android application.'
  private_lane :build do |options|
    gradle(task: 'clean', project_dir: './')
    gradle(
        task: 'assemble',
        build_type: 'Release',
        project_dir: './',
        )
  end

  desc 'Build for app center.'
  lane :build_app_center do
    build()
    appcenter_upload(
      api_token: ENV['APPCENTER_API_TOKEN'],
      owner_name: ENV['APPCENTER_OWNER_NAME'],
      app_name: "ExerciseTimer",
      apk: "./app/build/outputs/apk/release/app-release.apk",
      notify_testers: true,
      destinations: 'Collaborators'
    )
  end

  desc 'Prepare version code for next release'
  lane :bump_version do |options|
    gradle(task: 'bumpVersionCode', project_dir: './')
    version_properties_file_path = "./app/version.properties"
    properties = property_file_read(file: version_properties_file_path)
    git_commit(
      path: version_properties_file_path,
      message: ":bookmark: :robot: Build bump #{properties['VERSION_CODE']}"
    )
  end
end
